name: Building executable .jar files

on:
  push:
  pull_request:

jobs:
  build-jars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up EclispeTemurin JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.0.2
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Upload jar files
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: |
            Server/target/INF3405-Server.jar
            Client/target/INF3405-Client.jar
